//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FengSharp.OneCardAccess.Services.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FengSharp.OneCardAccess.Services.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 新增{0}失败 的本地化字符串。
        /// </summary>
        internal static string Error_AddFailed {
            get {
                return ResourceManager.GetString("Error_AddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检验报告模板名称不可为空 的本地化字符串。
        /// </summary>
        internal static string Error_CRTempNameCanNotEmpty {
            get {
                return ResourceManager.GetString("Error_CRTempNameCanNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除失败 的本地化字符串。
        /// </summary>
        internal static string Error_DeleteFailed {
            get {
                return ResourceManager.GetString("Error_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 附件路径未正确设置 的本地化字符串。
        /// </summary>
        internal static string Error_FileAttachDir {
            get {
                return ResourceManager.GetString("Error_FileAttachDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件不存在 的本地化字符串。
        /// </summary>
        internal static string Error_FileNotFound {
            get {
                return ResourceManager.GetString("Error_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未正确设置文件保存目录 的本地化字符串。
        /// </summary>
        internal static string Error_FileSaveDir {
            get {
                return ResourceManager.GetString("Error_FileSaveDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}正在使用 的本地化字符串。
        /// </summary>
        internal static string Error_IsUsing {
            get {
                return ResourceManager.GetString("Error_IsUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存{0}失败 的本地化字符串。
        /// </summary>
        internal static string Error_ModifyFailed {
            get {
                return ResourceManager.GetString("Error_ModifyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称已存在 的本地化字符串。
        /// </summary>
        internal static string Error_NameIsExist {
            get {
                return ResourceManager.GetString("Error_NameIsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编号不可为空 的本地化字符串。
        /// </summary>
        internal static string Error_NoCanNotEmpty {
            get {
                return ResourceManager.GetString("Error_NoCanNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编号已存在 的本地化字符串。
        /// </summary>
        internal static string Error_NoIsExist {
            get {
                return ResourceManager.GetString("Error_NoIsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编号不存在 的本地化字符串。
        /// </summary>
        internal static string Error_NoIsNotExist {
            get {
                return ResourceManager.GetString("Error_NoIsNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}已不存在 的本地化字符串。
        /// </summary>
        internal static string Error_ObjIsNotExist {
            get {
                return ResourceManager.GetString("Error_ObjIsNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册证名称不可为空 的本地化字符串。
        /// </summary>
        internal static string Error_RegisterNameCanNotEmpty {
            get {
                return ResourceManager.GetString("Error_RegisterNameCanNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存失败 的本地化字符串。
        /// </summary>
        internal static string Error_SaveFailed {
            get {
                return ResourceManager.GetString("Error_SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件流不可读 的本地化字符串。
        /// </summary>
        internal static string Error_StreamCanNotRead {
            get {
                return ResourceManager.GetString("Error_StreamCanNotRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件流为空 的本地化字符串。
        /// </summary>
        internal static string Error_StreamIsEmpty {
            get {
                return ResourceManager.GetString("Error_StreamIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超级用户组不可删除 的本地化字符串。
        /// </summary>
        internal static string Error_SuperUserGroupCanNotDelete {
            get {
                return ResourceManager.GetString("Error_SuperUserGroupCanNotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未处理的错误 的本地化字符串。
        /// </summary>
        internal static string Error_UnHandleException {
            get {
                return ResourceManager.GetString("Error_UnHandleException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户组名称不可为空 的本地化字符串。
        /// </summary>
        internal static string Error_UserGroupNameCanNotEmpty {
            get {
                return ResourceManager.GetString("Error_UserGroupNameCanNotEmpty", resourceCulture);
            }
        }
    }
}
