//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FengSharp.OneCardAccess.Client.PC.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FengSharp.OneCardAccess.Client.PC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 苏州康力骨科器械有限公公司 的本地化字符串。
        /// </summary>
        public static string CompanyRight_ComanyName {
            get {
                return ResourceManager.GetString("CompanyRight_ComanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保留所有权限 的本地化字符串。
        /// </summary>
        public static string CompanyRight_RightInfo {
            get {
                return ResourceManager.GetString("CompanyRight_RightInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动中... 的本地化字符串。
        /// </summary>
        public static string CompanyRight_StartInfo {
            get {
                return ResourceManager.GetString("CompanyRight_StartInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一卡通管理系统 的本地化字符串。
        /// </summary>
        public static string CompanyRight_SystemName {
            get {
                return ResourceManager.GetString("CompanyRight_SystemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有最好只有更好 的本地化字符串。
        /// </summary>
        public static string CompanyRight_Title {
            get {
                return ResourceManager.GetString("CompanyRight_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码错误 的本地化字符串。
        /// </summary>
        public static string ErrorPassWord {
            get {
                return ResourceManager.GetString("ErrorPassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎登录 的本地化字符串。
        /// </summary>
        public static string LoginFormTItle {
            get {
                return ResourceManager.GetString("LoginFormTItle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一卡通管理系统 的本地化字符串。
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误提示 的本地化字符串。
        /// </summary>
        public static string MessageBoxError {
            get {
                return ResourceManager.GetString("MessageBoxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码： 的本地化字符串。
        /// </summary>
        public static string PassWord {
            get {
                return ResourceManager.GetString("PassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户被锁定 的本地化字符串。
        /// </summary>
        public static string UserIsLocked {
            get {
                return ResourceManager.GetString("UserIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名： 的本地化字符串。
        /// </summary>
        public static string UserNo {
            get {
                return ResourceManager.GetString("UserNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户不存在 的本地化字符串。
        /// </summary>
        public static string UserNotExist {
            get {
                return ResourceManager.GetString("UserNotExist", resourceCulture);
            }
        }
    }
}
