//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FengSharp.OneCardAccess.Client.PC.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FengSharp.OneCardAccess.Client.PC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 新增 的本地化字符串。
        /// </summary>
        public static string AddBarContent {
            get {
                return ResourceManager.GetString("AddBarContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        public static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分类 的本地化字符串。
        /// </summary>
        public static string CateBarContent {
            get {
                return ResourceManager.GetString("CateBarContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string CloseBarContent {
            get {
                return ResourceManager.GetString("CloseBarContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 苏州康力骨科器械有限公公司 的本地化字符串。
        /// </summary>
        public static string CompanyRight_ComanyName {
            get {
                return ResourceManager.GetString("CompanyRight_ComanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保留所有权限 的本地化字符串。
        /// </summary>
        public static string CompanyRight_RightInfo {
            get {
                return ResourceManager.GetString("CompanyRight_RightInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动中... 的本地化字符串。
        /// </summary>
        public static string CompanyRight_StartInfo {
            get {
                return ResourceManager.GetString("CompanyRight_StartInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一卡通管理系统 的本地化字符串。
        /// </summary>
        public static string CompanyRight_SystemName {
            get {
                return ResourceManager.GetString("CompanyRight_SystemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有最好只有更好 的本地化字符串。
        /// </summary>
        public static string CompanyRight_Title {
            get {
                return ResourceManager.GetString("CompanyRight_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确实要退出吗？ 的本地化字符串。
        /// </summary>
        public static string ConfirmToExit {
            get {
                return ResourceManager.GetString("ConfirmToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制新增 的本地化字符串。
        /// </summary>
        public static string CopyAddBarContent {
            get {
                return ResourceManager.GetString("CopyAddBarContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string DeleteBarContent {
            get {
                return ResourceManager.GetString("DeleteBarContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string EditBarContent {
            get {
                return ResourceManager.GetString("EditBarContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码错误 的本地化字符串。
        /// </summary>
        public static string ErrorPassWord {
            get {
                return ResourceManager.GetString("ErrorPassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎登录-一卡通系统 的本地化字符串。
        /// </summary>
        public static string LoginView_Title {
            get {
                return ResourceManager.GetString("LoginView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一卡通管理系统 的本地化字符串。
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册证信息 的本地化字符串。
        /// </summary>
        public static string Menu_Register {
            get {
                return ResourceManager.GetString("Menu_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导航 的本地化字符串。
        /// </summary>
        public static string Menu_RibbonPage_Navigate {
            get {
                return ResourceManager.GetString("Menu_RibbonPage_Navigate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基本信息 的本地化字符串。
        /// </summary>
        public static string Menu_RibbonPageGroup_BasicInfo {
            get {
                return ResourceManager.GetString("Menu_RibbonPageGroup_BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误提示 的本地化字符串。
        /// </summary>
        public static string MessageBoxError {
            get {
                return ResourceManager.GetString("MessageBoxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        public static string MessageBoxTip {
            get {
                return ResourceManager.GetString("MessageBoxTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数错误 的本地化字符串。
        /// </summary>
        public static string ParaMeterIsError {
            get {
                return ResourceManager.GetString("ParaMeterIsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码： 的本地化字符串。
        /// </summary>
        public static string PassWord {
            get {
                return ResourceManager.GetString("PassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册证信息 的本地化字符串。
        /// </summary>
        public static string RegisterCollectionView_Title {
            get {
                return ResourceManager.GetString("RegisterCollectionView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品注册证编辑 的本地化字符串。
        /// </summary>
        public static string RegisterView_Title {
            get {
                return ResourceManager.GetString("RegisterView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回 的本地化字符串。
        /// </summary>
        public static string ReturnBarContent {
            get {
                return ResourceManager.GetString("ReturnBarContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存并继续 的本地化字符串。
        /// </summary>
        public static string SaveAndNewBarContent {
            get {
                return ResourceManager.GetString("SaveAndNewBarContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string SaveBarContent {
            get {
                return ResourceManager.GetString("SaveBarContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户被锁定 的本地化字符串。
        /// </summary>
        public static string UserIsLocked {
            get {
                return ResourceManager.GetString("UserIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名： 的本地化字符串。
        /// </summary>
        public static string UserNo {
            get {
                return ResourceManager.GetString("UserNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户不存在 的本地化字符串。
        /// </summary>
        public static string UserNotExist {
            get {
                return ResourceManager.GetString("UserNotExist", resourceCulture);
            }
        }
    }
}
