//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FengSharp.OneCardAccess.Client.PC.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FengSharp.OneCardAccess.Client.PC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 新增 的本地化字符串。
        /// </summary>
        public static string BarContent_Add {
            get {
                return ResourceManager.GetString("BarContent_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增子项 的本地化字符串。
        /// </summary>
        public static string BarContent_AddChild {
            get {
                return ResourceManager.GetString("BarContent_AddChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分类 的本地化字符串。
        /// </summary>
        public static string BarContent_Cate {
            get {
                return ResourceManager.GetString("BarContent_Cate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string BarContent_Close {
            get {
                return ResourceManager.GetString("BarContent_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string BarContent_Confirm {
            get {
                return ResourceManager.GetString("BarContent_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制新增 的本地化字符串。
        /// </summary>
        public static string BarContent_CopyAdd {
            get {
                return ResourceManager.GetString("BarContent_CopyAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string BarContent_Delete {
            get {
                return ResourceManager.GetString("BarContent_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string BarContent_Edit {
            get {
                return ResourceManager.GetString("BarContent_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下移 的本地化字符串。
        /// </summary>
        public static string BarContent_MoveDown {
            get {
                return ResourceManager.GetString("BarContent_MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上移 的本地化字符串。
        /// </summary>
        public static string BarContent_MoveUp {
            get {
                return ResourceManager.GetString("BarContent_MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回 的本地化字符串。
        /// </summary>
        public static string BarContent_Return {
            get {
                return ResourceManager.GetString("BarContent_Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string BarContent_Save {
            get {
                return ResourceManager.GetString("BarContent_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存并继续 的本地化字符串。
        /// </summary>
        public static string BarContent_SaveAndNew {
            get {
                return ResourceManager.GetString("BarContent_SaveAndNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传 的本地化字符串。
        /// </summary>
        public static string BarContent_UpLoad {
            get {
                return ResourceManager.GetString("BarContent_UpLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string btn_Close {
            get {
                return ResourceManager.GetString("btn_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制错误 的本地化字符串。
        /// </summary>
        public static string btn_CopyError {
            get {
                return ResourceManager.GetString("btn_CopyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 苏州康力骨科器械有限公公司 的本地化字符串。
        /// </summary>
        public static string CompanyRight_ComanyName {
            get {
                return ResourceManager.GetString("CompanyRight_ComanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保留所有权限 的本地化字符串。
        /// </summary>
        public static string CompanyRight_RightInfo {
            get {
                return ResourceManager.GetString("CompanyRight_RightInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动中... 的本地化字符串。
        /// </summary>
        public static string CompanyRight_StartInfo {
            get {
                return ResourceManager.GetString("CompanyRight_StartInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一卡通管理系统 的本地化字符串。
        /// </summary>
        public static string CompanyRight_SystemName {
            get {
                return ResourceManager.GetString("CompanyRight_SystemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有最好只有更好 的本地化字符串。
        /// </summary>
        public static string CompanyRight_Title {
            get {
                return ResourceManager.GetString("CompanyRight_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   的本地化字符串。
        /// </summary>
        public static string EmptyString {
            get {
                return ResourceManager.GetString("EmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类别号 的本地化字符串。
        /// </summary>
        public static string Entity_P_CRTemp_CateNo {
            get {
                return ResourceManager.GetString("Entity_P_CRTemp_CateNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建日期 的本地化字符串。
        /// </summary>
        public static string Entity_P_CRTemp_CreateDate {
            get {
                return ResourceManager.GetString("Entity_P_CRTemp_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建人 的本地化字符串。
        /// </summary>
        public static string Entity_P_CRTemp_Creater {
            get {
                return ResourceManager.GetString("Entity_P_CRTemp_Creater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板名称 的本地化字符串。
        /// </summary>
        public static string Entity_P_CRTemp_CRTempName {
            get {
                return ResourceManager.GetString("Entity_P_CRTemp_CRTempName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路径 的本地化字符串。
        /// </summary>
        public static string Entity_P_CRTemp_CRTempPath {
            get {
                return ResourceManager.GetString("Entity_P_CRTemp_CRTempPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否启用 的本地化字符串。
        /// </summary>
        public static string Entity_P_CRTemp_IsEnable {
            get {
                return ResourceManager.GetString("Entity_P_CRTemp_IsEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后更改日期 的本地化字符串。
        /// </summary>
        public static string Entity_P_CRTemp_LastModifyDate {
            get {
                return ResourceManager.GetString("Entity_P_CRTemp_LastModifyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后更改人 的本地化字符串。
        /// </summary>
        public static string Entity_P_CRTemp_LastModifyer {
            get {
                return ResourceManager.GetString("Entity_P_CRTemp_LastModifyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 材料标识 的本地化字符串。
        /// </summary>
        public static string Entity_P_CRTemp_MaterIden {
            get {
                return ResourceManager.GetString("Entity_P_CRTemp_MaterIden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        public static string Entity_P_CRTemp_Remark {
            get {
                return ResourceManager.GetString("Entity_P_CRTemp_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板名称 的本地化字符串。
        /// </summary>
        public static string Entity_P_CRTemp_To_RegisterEntity_CRTempName {
            get {
                return ResourceManager.GetString("Entity_P_CRTemp_To_RegisterEntity_CRTempName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        public static string Entity_P_CRTemp_To_RegisterEntity_Remark {
            get {
                return ResourceManager.GetString("Entity_P_CRTemp_To_RegisterEntity_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建日期 的本地化字符串。
        /// </summary>
        public static string Entity_Register_CreateDate {
            get {
                return ResourceManager.GetString("Entity_Register_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建人 的本地化字符串。
        /// </summary>
        public static string Entity_Register_Creater {
            get {
                return ResourceManager.GetString("Entity_Register_Creater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停用日期 的本地化字符串。
        /// </summary>
        public static string Entity_Register_EndDate {
            get {
                return ResourceManager.GetString("Entity_Register_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件名 的本地化字符串。
        /// </summary>
        public static string Entity_Register_File_FileName {
            get {
                return ResourceManager.GetString("Entity_Register_File_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存路径 的本地化字符串。
        /// </summary>
        public static string Entity_Register_File_FilePath {
            get {
                return ResourceManager.GetString("Entity_Register_File_FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序号 的本地化字符串。
        /// </summary>
        public static string Entity_Register_File_SortNo {
            get {
                return ResourceManager.GetString("Entity_Register_File_SortNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后更改日期 的本地化字符串。
        /// </summary>
        public static string Entity_Register_LastModifyDate {
            get {
                return ResourceManager.GetString("Entity_Register_LastModifyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后更改人 的本地化字符串。
        /// </summary>
        public static string Entity_Register_LastModifyer {
            get {
                return ResourceManager.GetString("Entity_Register_LastModifyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册证名称 的本地化字符串。
        /// </summary>
        public static string Entity_Register_RegisterName {
            get {
                return ResourceManager.GetString("Entity_Register_RegisterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册证名称(英文) 的本地化字符串。
        /// </summary>
        public static string Entity_Register_RegisterName1 {
            get {
                return ResourceManager.GetString("Entity_Register_RegisterName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册证编号 的本地化字符串。
        /// </summary>
        public static string Entity_Register_RegisterNo {
            get {
                return ResourceManager.GetString("Entity_Register_RegisterNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册证编号(英文) 的本地化字符串。
        /// </summary>
        public static string Entity_Register_RegisterNo1 {
            get {
                return ResourceManager.GetString("Entity_Register_RegisterNo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        public static string Entity_Register_Remark {
            get {
                return ResourceManager.GetString("Entity_Register_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标准号 的本地化字符串。
        /// </summary>
        public static string Entity_Register_StandardCode {
            get {
                return ResourceManager.GetString("Entity_Register_StandardCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标准号(英文) 的本地化字符串。
        /// </summary>
        public static string Entity_Register_StandardCode1 {
            get {
                return ResourceManager.GetString("Entity_Register_StandardCode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用日期 的本地化字符串。
        /// </summary>
        public static string Entity_Register_StartDate {
            get {
                return ResourceManager.GetString("Entity_Register_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建日期 的本地化字符串。
        /// </summary>
        public static string Entity_UserGroup_CreateDate {
            get {
                return ResourceManager.GetString("Entity_UserGroup_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建人 的本地化字符串。
        /// </summary>
        public static string Entity_UserGroup_Creater {
            get {
                return ResourceManager.GetString("Entity_UserGroup_Creater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锁定标识 的本地化字符串。
        /// </summary>
        public static string Entity_UserGroup_IsLock {
            get {
                return ResourceManager.GetString("Entity_UserGroup_IsLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超级管理组 的本地化字符串。
        /// </summary>
        public static string Entity_UserGroup_IsSuper {
            get {
                return ResourceManager.GetString("Entity_UserGroup_IsSuper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后更改日期 的本地化字符串。
        /// </summary>
        public static string Entity_UserGroup_LastModifyDate {
            get {
                return ResourceManager.GetString("Entity_UserGroup_LastModifyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后更改人 的本地化字符串。
        /// </summary>
        public static string Entity_UserGroup_LastModifyer {
            get {
                return ResourceManager.GetString("Entity_UserGroup_LastModifyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        public static string Entity_UserGroup_Remark {
            get {
                return ResourceManager.GetString("Entity_UserGroup_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户组名称 的本地化字符串。
        /// </summary>
        public static string Entity_UserGroup_UserGroupName {
            get {
                return ResourceManager.GetString("Entity_UserGroup_UserGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户组编号 的本地化字符串。
        /// </summary>
        public static string Entity_UserGroup_UserGroupNo {
            get {
                return ResourceManager.GetString("Entity_UserGroup_UserGroupNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建日期 的本地化字符串。
        /// </summary>
        public static string Entity_UserInfo_CreateDate {
            get {
                return ResourceManager.GetString("Entity_UserInfo_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建人 的本地化字符串。
        /// </summary>
        public static string Entity_UserInfo_Creater {
            get {
                return ResourceManager.GetString("Entity_UserInfo_Creater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锁定标识 的本地化字符串。
        /// </summary>
        public static string Entity_UserInfo_IsLock {
            get {
                return ResourceManager.GetString("Entity_UserInfo_IsLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后更改日期 的本地化字符串。
        /// </summary>
        public static string Entity_UserInfo_LastModifyDate {
            get {
                return ResourceManager.GetString("Entity_UserInfo_LastModifyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后更改人 的本地化字符串。
        /// </summary>
        public static string Entity_UserInfo_LastModifyer {
            get {
                return ResourceManager.GetString("Entity_UserInfo_LastModifyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        public static string Entity_UserInfo_PassWord {
            get {
                return ResourceManager.GetString("Entity_UserInfo_PassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        public static string Entity_UserInfo_Remark {
            get {
                return ResourceManager.GetString("Entity_UserInfo_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组名称 的本地化字符串。
        /// </summary>
        public static string Entity_UserInfo_UserGroupName {
            get {
                return ResourceManager.GetString("Entity_UserInfo_UserGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组编号 的本地化字符串。
        /// </summary>
        public static string Entity_UserInfo_UserGroupNo {
            get {
                return ResourceManager.GetString("Entity_UserInfo_UserGroupNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户姓名 的本地化字符串。
        /// </summary>
        public static string Entity_UserInfo_UserName {
            get {
                return ResourceManager.GetString("Entity_UserInfo_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户账号 的本地化字符串。
        /// </summary>
        public static string Entity_UserInfo_UserNo {
            get {
                return ResourceManager.GetString("Entity_UserInfo_UserNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务或客户端应用程序中的通信错误 的本地化字符串。
        /// </summary>
        public static string Error_CommunicationException {
            get {
                return ResourceManager.GetString("Error_CommunicationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接服务器失败 的本地化字符串。
        /// </summary>
        public static string Error_ConnectionServerFailed {
            get {
                return ResourceManager.GetString("Error_ConnectionServerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 父节点不可为空 的本地化字符串。
        /// </summary>
        public static string Error_FatherCanNotEmpty {
            get {
                return ResourceManager.GetString("Error_FatherCanNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录超时 的本地化字符串。
        /// </summary>
        public static string Error_LoginTimeOut {
            get {
                return ResourceManager.GetString("Error_LoginTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数错误 的本地化字符串。
        /// </summary>
        public static string Error_ParameterIsError {
            get {
                return ResourceManager.GetString("Error_ParameterIsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码错误 的本地化字符串。
        /// </summary>
        public static string Error_PassWordIsError {
            get {
                return ResourceManager.GetString("Error_PassWordIsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存失败 的本地化字符串。
        /// </summary>
        public static string Error_SaveFiled {
            get {
                return ResourceManager.GetString("Error_SaveFiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务内部出错 的本地化字符串。
        /// </summary>
        public static string Error_ServerException {
            get {
                return ResourceManager.GetString("Error_ServerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误提示 的本地化字符串。
        /// </summary>
        public static string Error_Title {
            get {
                return ResourceManager.GetString("Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的会话 的本地化字符串。
        /// </summary>
        public static string Error_UnableSession {
            get {
                return ResourceManager.GetString("Error_UnableSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未经处理的异常 的本地化字符串。
        /// </summary>
        public static string Error_UnHandler {
            get {
                return ResourceManager.GetString("Error_UnHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不正确的用户配置键 的本地化字符串。
        /// </summary>
        public static string Error_UserConfigKey {
            get {
                return ResourceManager.GetString("Error_UserConfigKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名为空 的本地化字符串。
        /// </summary>
        public static string Error_UserIsEmpty {
            get {
                return ResourceManager.GetString("Error_UserIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户被锁定 的本地化字符串。
        /// </summary>
        public static string Error_UserIsLocked {
            get {
                return ResourceManager.GetString("Error_UserIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户不存在 的本地化字符串。
        /// </summary>
        public static string Error_UserNotExist {
            get {
                return ResourceManager.GetString("Error_UserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 yyyy年MM月dd日 的本地化字符串。
        /// </summary>
        public static string Format_DateString {
            get {
                return ResourceManager.GetString("Format_DateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 yyyy年MM月dd日 HH:mm:ss 的本地化字符串。
        /// </summary>
        public static string Format_TimeString {
            get {
                return ResourceManager.GetString("Format_TimeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确实要删除吗？ 的本地化字符串。
        /// </summary>
        public static string Info_ConfirmToDelete {
            get {
                return ResourceManager.GetString("Info_ConfirmToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确实要退出吗？ 的本地化字符串。
        /// </summary>
        public static string Info_ConfirmToExit {
            get {
                return ResourceManager.GetString("Info_ConfirmToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除成功 的本地化字符串。
        /// </summary>
        public static string Info_DeleteSuccess {
            get {
                return ResourceManager.GetString("Info_DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件不存在 的本地化字符串。
        /// </summary>
        public static string Info_FileNotFound {
            get {
                return ResourceManager.GetString("Info_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载中... 的本地化字符串。
        /// </summary>
        public static string Info_Loading {
            get {
                return ResourceManager.GetString("Info_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有下一条记录了 的本地化字符串。
        /// </summary>
        public static string Info_NoNext {
            get {
                return ResourceManager.GetString("Info_NoNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请稍后 的本地化字符串。
        /// </summary>
        public static string Info_PleaseWait {
            get {
                return ResourceManager.GetString("Info_PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存成功 的本地化字符串。
        /// </summary>
        public static string Info_SaveSuccess {
            get {
                return ResourceManager.GetString("Info_SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 至少选择一项 的本地化字符串。
        /// </summary>
        public static string Info_SelectAtLeastOne {
            get {
                return ResourceManager.GetString("Info_SelectAtLeastOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        public static string Info_Title {
            get {
                return ResourceManager.GetString("Info_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传成功 的本地化字符串。
        /// </summary>
        public static string Info_UploadSuccess {
            get {
                return ResourceManager.GetString("Info_UploadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品检验报告模板 的本地化字符串。
        /// </summary>
        public static string Menu_P_CRTemp {
            get {
                return ResourceManager.GetString("Menu_P_CRTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册证信息 的本地化字符串。
        /// </summary>
        public static string Menu_Register {
            get {
                return ResourceManager.GetString("Menu_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导航 的本地化字符串。
        /// </summary>
        public static string Menu_RibbonPage_Navigate {
            get {
                return ResourceManager.GetString("Menu_RibbonPage_Navigate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基本信息 的本地化字符串。
        /// </summary>
        public static string Menu_RibbonPageGroup_BasicInfo {
            get {
                return ResourceManager.GetString("Menu_RibbonPageGroup_BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户权限 的本地化字符串。
        /// </summary>
        public static string Menu_RibbonPageGroup_RBAC {
            get {
                return ResourceManager.GetString("Menu_RibbonPageGroup_RBAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户组管理 的本地化字符串。
        /// </summary>
        public static string Menu_UserAndGroupManager {
            get {
                return ResourceManager.GetString("Menu_UserAndGroupManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户信息 的本地化字符串。
        /// </summary>
        public static string Menu_UserCollectionView {
            get {
                return ResourceManager.GetString("Menu_UserCollectionView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户组 的本地化字符串。
        /// </summary>
        public static string Menu_UserGroupCollectionView {
            get {
                return ResourceManager.GetString("Menu_UserGroupCollectionView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户信息操作 的本地化字符串。
        /// </summary>
        public static string ToolBar_UserCollectionView_OP {
            get {
                return ResourceManager.GetString("ToolBar_UserCollectionView_OP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户组操作 的本地化字符串。
        /// </summary>
        public static string ToolBar_UserGroupCollectionView_OP {
            get {
                return ResourceManager.GetString("ToolBar_UserGroupCollectionView_OP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string View_LoginView_btnCancel_Content {
            get {
                return ResourceManager.GetString("View_LoginView_btnCancel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        public static string View_LoginView_btnLogin_Content {
            get {
                return ResourceManager.GetString("View_LoginView_btnLogin_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        public static string View_LoginView_lblPassWord_Label {
            get {
                return ResourceManager.GetString("View_LoginView_lblPassWord_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        public static string View_LoginView_lblUserNo_Label {
            get {
                return ResourceManager.GetString("View_LoginView_lblUserNo_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎登录-一卡通系统 的本地化字符串。
        /// </summary>
        public static string View_LoginView_Title {
            get {
                return ResourceManager.GetString("View_LoginView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一卡通管理系统 的本地化字符串。
        /// </summary>
        public static string View_MainWindow_Title {
            get {
                return ResourceManager.GetString("View_MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检验报告模板 的本地化字符串。
        /// </summary>
        public static string View_P_CRTempView_P_CRTempImage {
            get {
                return ResourceManager.GetString("View_P_CRTempView_P_CRTempImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品检验报告模板 的本地化字符串。
        /// </summary>
        public static string View_P_CRTempView_Title {
            get {
                return ResourceManager.GetString("View_P_CRTempView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册证信息 的本地化字符串。
        /// </summary>
        public static string View_RegisterCollectionView_Title {
            get {
                return ResourceManager.GetString("View_RegisterCollectionView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 附件 的本地化字符串。
        /// </summary>
        public static string View_RegisterView_lgRegisterFile_Header {
            get {
                return ResourceManager.GetString("View_RegisterView_lgRegisterFile_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检验报告模板 的本地化字符串。
        /// </summary>
        public static string View_RegisterView_lgTemplate_Header {
            get {
                return ResourceManager.GetString("View_RegisterView_lgTemplate_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册证附件操作 的本地化字符串。
        /// </summary>
        public static string View_RegisterView_rpgRegisterFile_Caption {
            get {
                return ResourceManager.GetString("View_RegisterView_rpgRegisterFile_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检验报告模板操作 的本地化字符串。
        /// </summary>
        public static string View_RegisterView_rpgTemplate_Caption {
            get {
                return ResourceManager.GetString("View_RegisterView_rpgTemplate_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品注册证编辑 的本地化字符串。
        /// </summary>
        public static string View_RegisterView_Title {
            get {
                return ResourceManager.GetString("View_RegisterView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户组管理 的本地化字符串。
        /// </summary>
        public static string View_UserAndGroupManagerView_Title {
            get {
                return ResourceManager.GetString("View_UserAndGroupManagerView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户信息管理 的本地化字符串。
        /// </summary>
        public static string View_UserCollectionView_Title {
            get {
                return ResourceManager.GetString("View_UserCollectionView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户组 的本地化字符串。
        /// </summary>
        public static string View_UserGroupCollectionView_Title {
            get {
                return ResourceManager.GetString("View_UserGroupCollectionView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户组编辑 的本地化字符串。
        /// </summary>
        public static string View_UserGroupView_Title {
            get {
                return ResourceManager.GetString("View_UserGroupView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户信息 的本地化字符串。
        /// </summary>
        public static string View_UserView_Title {
            get {
                return ResourceManager.GetString("View_UserView_Title", resourceCulture);
            }
        }
    }
}
