//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExpress.Xpf.WpfReportDesignerLanguage.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevExpress.Xpf.WpfReportDesignerLanguage.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 排列 的本地化字符串。
        /// </summary>
        public static string WpfReportDesignerStringId_ArrangeGroup {
            get {
                return ResourceManager.GetString("WpfReportDesignerStringId_ArrangeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移到上一层 的本地化字符串。
        /// </summary>
        public static string WpfReportDesignerStringId_BringFront {
            get {
                return ResourceManager.GetString("WpfReportDesignerStringId_BringFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 置于顶层 的本地化字符串。
        /// </summary>
        public static string WpfReportDesignerStringId_BringtoFront {
            get {
                return ResourceManager.GetString("WpfReportDesignerStringId_BringtoFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单元格 的本地化字符串。
        /// </summary>
        public static string WpfReportDesignerStringId_Cell {
            get {
                return ResourceManager.GetString("WpfReportDesignerStringId_Cell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列 的本地化字符串。
        /// </summary>
        public static string WpfReportDesignerStringId_Column {
            get {
                return ResourceManager.GetString("WpfReportDesignerStringId_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列左 的本地化字符串。
        /// </summary>
        public static string WpfReportDesignerStringId_ColumnToLeft {
            get {
                return ResourceManager.GetString("WpfReportDesignerStringId_ColumnToLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列右 的本地化字符串。
        /// </summary>
        public static string WpfReportDesignerStringId_ColumnToRight {
            get {
                return ResourceManager.GetString("WpfReportDesignerStringId_ColumnToRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        public static string WpfReportDesignerStringId_Copy {
            get {
                return ResourceManager.GetString("WpfReportDesignerStringId_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剪切 的本地化字符串。
        /// </summary>
        public static string WpfReportDesignerStringId_Cut {
            get {
                return ResourceManager.GetString("WpfReportDesignerStringId_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string WpfReportDesignerStringId_Delete {
            get {
                return ResourceManager.GetString("WpfReportDesignerStringId_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string WpfReportDesignerStringId_EditGroup {
            get {
                return ResourceManager.GetString("WpfReportDesignerStringId_EditGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 精确 的本地化字符串。
        /// </summary>
        public static string WpfReportDesignerStringId_Exact {
            get {
                return ResourceManager.GetString("WpfReportDesignerStringId_Exact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        public static string WpfReportDesignerStringId_Exit {
            get {
                return ResourceManager.GetString("WpfReportDesignerStringId_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可用字段 的本地化字符串。
        /// </summary>
        public static string WpfReportDesignerStringId_FieldList {
            get {
                return ResourceManager.GetString("WpfReportDesignerStringId_FieldList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字体 的本地化字符串。
        /// </summary>
        public static string WpfReportDesignerStringId_FontGroup {
            get {
                return ResourceManager.GetString("WpfReportDesignerStringId_FontGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组尾 的本地化字符串。
        /// </summary>
        public static string WpfReportDesignerStringId_GroupFooter {
            get {
                return ResourceManager.GetString("WpfReportDesignerStringId_GroupFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组头 的本地化字符串。
        /// </summary>
        public static string WpfReportDesignerStringId_GroupHeader {
            get {
                return ResourceManager.GetString("WpfReportDesignerStringId_GroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插入 的本地化字符串。
        /// </summary>
        public static string WpfReportDesignerStringId_Insert {
            get {
                return ResourceManager.GetString("WpfReportDesignerStringId_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插入绑定 的本地化字符串。
        /// </summary>
        public static string WpfReportDesignerStringId_InsertBand {
            get {
                return ResourceManager.GetString("WpfReportDesignerStringId_InsertBand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插入报表详细 的本地化字符串。
        /// </summary>
        public static string WpfReportDesignerStringId_InsertDetailReport {
            get {
                return ResourceManager.GetString("WpfReportDesignerStringId_InsertDetailReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建报表 的本地化字符串。
        /// </summary>
        public static string WpfReportDesignerStringId_NewReport {
            get {
                return ResourceManager.GetString("WpfReportDesignerStringId_NewReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开报表 的本地化字符串。
        /// </summary>
        public static string WpfReportDesignerStringId_OpenReport {
            get {
                return ResourceManager.GetString("WpfReportDesignerStringId_OpenReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页尾 的本地化字符串。
        /// </summary>
        public static string WpfReportDesignerStringId_PageFooter {
            get {
                return ResourceManager.GetString("WpfReportDesignerStringId_PageFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页头 的本地化字符串。
        /// </summary>
        public static string WpfReportDesignerStringId_PageHeader {
            get {
                return ResourceManager.GetString("WpfReportDesignerStringId_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粘贴 的本地化字符串。
        /// </summary>
        public static string WpfReportDesignerStringId_Paste {
            get {
                return ResourceManager.GetString("WpfReportDesignerStringId_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预览 的本地化字符串。
        /// </summary>
        public static string WpfReportDesignerStringId_Preview {
            get {
                return ResourceManager.GetString("WpfReportDesignerStringId_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性 的本地化字符串。
        /// </summary>
        public static string WpfReportDesignerStringId_PropertExplorer {
            get {
                return ResourceManager.GetString("WpfReportDesignerStringId_PropertExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性 的本地化字符串。
        /// </summary>
        public static string WpfReportDesignerStringId_Properties {
            get {
                return ResourceManager.GetString("WpfReportDesignerStringId_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恢复 的本地化字符串。
        /// </summary>
        public static string WpfReportDesignerStringId_Redo {
            get {
                return ResourceManager.GetString("WpfReportDesignerStringId_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报表浏览 的本地化字符串。
        /// </summary>
        public static string WpfReportDesignerStringId_ReportExplorer {
            get {
                return ResourceManager.GetString("WpfReportDesignerStringId_ReportExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表尾 的本地化字符串。
        /// </summary>
        public static string WpfReportDesignerStringId_ReportFooter {
            get {
                return ResourceManager.GetString("WpfReportDesignerStringId_ReportFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报表 的本地化字符串。
        /// </summary>
        public static string WpfReportDesignerStringId_ReportGroup {
            get {
                return ResourceManager.GetString("WpfReportDesignerStringId_ReportGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表头 的本地化字符串。
        /// </summary>
        public static string WpfReportDesignerStringId_ReportHeader {
            get {
                return ResourceManager.GetString("WpfReportDesignerStringId_ReportHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行 的本地化字符串。
        /// </summary>
        public static string WpfReportDesignerStringId_Row {
            get {
                return ResourceManager.GetString("WpfReportDesignerStringId_Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行上 的本地化字符串。
        /// </summary>
        public static string WpfReportDesignerStringId_RowAbove {
            get {
                return ResourceManager.GetString("WpfReportDesignerStringId_RowAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行下 的本地化字符串。
        /// </summary>
        public static string WpfReportDesignerStringId_RowBelow {
            get {
                return ResourceManager.GetString("WpfReportDesignerStringId_RowBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 另存为 的本地化字符串。
        /// </summary>
        public static string WpfReportDesignerStringId_SaveAsReport {
            get {
                return ResourceManager.GetString("WpfReportDesignerStringId_SaveAsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string WpfReportDesignerStringId_SaveReport {
            get {
                return ResourceManager.GetString("WpfReportDesignerStringId_SaveReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后移一层 的本地化字符串。
        /// </summary>
        public static string WpfReportDesignerStringId_SendBackward {
            get {
                return ResourceManager.GetString("WpfReportDesignerStringId_SendBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 置于最后 的本地化字符串。
        /// </summary>
        public static string WpfReportDesignerStringId_SendtoBack {
            get {
                return ResourceManager.GetString("WpfReportDesignerStringId_SendtoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报表设计 的本地化字符串。
        /// </summary>
        public static string WpfReportDesignerStringId_Title {
            get {
                return ResourceManager.GetString("WpfReportDesignerStringId_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未绑定 的本地化字符串。
        /// </summary>
        public static string WpfReportDesignerStringId_Unbound {
            get {
                return ResourceManager.GetString("WpfReportDesignerStringId_Unbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 撤销 的本地化字符串。
        /// </summary>
        public static string WpfReportDesignerStringId_Undo {
            get {
                return ResourceManager.GetString("WpfReportDesignerStringId_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩放 的本地化字符串。
        /// </summary>
        public static string WpfReportDesignerStringId_Zoom {
            get {
                return ResourceManager.GetString("WpfReportDesignerStringId_Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩放 的本地化字符串。
        /// </summary>
        public static string WpfReportDesignerStringId_ZoomGroup {
            get {
                return ResourceManager.GetString("WpfReportDesignerStringId_ZoomGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 放大 的本地化字符串。
        /// </summary>
        public static string WpfReportDesignerStringId_ZoomIn {
            get {
                return ResourceManager.GetString("WpfReportDesignerStringId_ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩小 的本地化字符串。
        /// </summary>
        public static string WpfReportDesignerStringId_ZoomOut {
            get {
                return ResourceManager.GetString("WpfReportDesignerStringId_ZoomOut", resourceCulture);
            }
        }
    }
}
